//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageBox_Test.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageBox_Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Chess {
            get {
                object obj = ResourceManager.GetObject("Chess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Lenna_24 {
            get {
                object obj = ResourceManager.GetObject("Lenna_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Lenna_32 {
            get {
                object obj = ResourceManager.GetObject("Lenna_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Lenna_8 {
            get {
                object obj = ResourceManager.GetObject("Lenna_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   0000:AAAA00018000000180004A51EA505A51C99E0001800000018000000180005555
        ///0001:AAAA00018000000180003993C252325F8A527193800000018000000180005555
        ///0002:AAAA00018000000180003BA5C124311989247125800000018000000180005555
        ///0003:AAAA00018000000180007BA5C1247919C1247925800000018000000180005555
        ///0004:AAAA000180000001800079BFC2487A49C2487989800000018000000180005555
        ///0005:AAAA00018000000180007A4DC2527B53C2D67A4F800000018000000180005555
        ///0006:AAAA000180000001800031A5CA287A31CA2849A5800000018000000180005555
        ///0007:AAAA0001800000018[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string unifont_13_0_06 {
            get {
                return ResourceManager.GetString("unifont_13_0_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0000:AAAA00018000000180004A51EA505A51C99E0001800000018000000180005555
        ///0001:AAAA00018000000180003993C252325F8A527193800000018000000180005555
        ///0002:AAAA00018000000180003BA5C124311989247125800000018000000180005555
        ///0003:AAAA00018000000180007BA5C1247919C1247925800000018000000180005555
        ///0004:AAAA000180000001800079BFC2487A49C2487989800000018000000180005555
        ///0005:AAAA00018000000180007A4DC2527B53C2D67A4F800000018000000180005555
        ///0006:AAAA000180000001800031A5CA287A31CA2849A5800000018000000180005555
        ///0007:AAAA0001800000018[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string unifont_sample_13_0_06 {
            get {
                return ResourceManager.GetString("unifont_sample_13_0_06", resourceCulture);
            }
        }
    }
}
