//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShimLib.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShimLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT /*
        ///COMMENT  * Spleen 5x8 1.9.1
        ///COMMENT  * Copyright (c) 2018-2021, Frederic Cambus
        ///COMMENT  * https://www.cambus.net/
        ///COMMENT  *
        ///COMMENT  * Created:      2018-08-08
        ///COMMENT  * Last Updated: 2021-03-10
        ///COMMENT  *
        ///COMMENT  * Spleen is released under the BSD 2-Clause license.
        ///COMMENT  * See LICENSE file for details.
        ///COMMENT  */
        ///FONT -misc-spleen-medium-r-normal--8-80-72-72-C-50-ISO10646-1
        ///SIZE 8 72 72
        ///FONTBOUNDINGBOX 5 8 0 -1
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Spleen&quot;
        ///WEIGHT[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string spleen_05x08 {
            get {
                return ResourceManager.GetString("spleen_05x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT /*
        ///COMMENT  * Spleen 6x12 1.9.1
        ///COMMENT  * Copyright (c) 2018-2021, Frederic Cambus
        ///COMMENT  * https://www.cambus.net/
        ///COMMENT  *
        ///COMMENT  * Created:      2020-04-08
        ///COMMENT  * Last Updated: 2021-03-12
        ///COMMENT  *
        ///COMMENT  * Spleen is released under the BSD 2-Clause license.
        ///COMMENT  * See LICENSE file for details.
        ///COMMENT  */
        ///FONT -misc-spleen-medium-r-normal--12-120-72-72-C-60-ISO10646-1
        ///SIZE 12 72 72
        ///FONTBOUNDINGBOX 6 12 0 -3
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Spleen&quot;
        ///W[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string spleen_06x12 {
            get {
                return ResourceManager.GetString("spleen_06x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT /*
        ///COMMENT  * Spleen 8x16 1.9.1
        ///COMMENT  * Copyright (c) 2018-2021, Frederic Cambus
        ///COMMENT  * https://www.cambus.net/
        ///COMMENT  *
        ///COMMENT  * Created:      2018-08-11
        ///COMMENT  * Last Updated: 2020-10-10
        ///COMMENT  *
        ///COMMENT  * Spleen is released under the BSD 2-Clause license.
        ///COMMENT  * See LICENSE file for details.
        ///COMMENT  */
        ///FONT -misc-spleen-medium-r-normal--16-160-72-72-C-80-ISO10646-1
        ///SIZE 16 72 72
        ///FONTBOUNDINGBOX 8 16 0 -4
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Spleen&quot;
        ///W[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string spleen_08x16 {
            get {
                return ResourceManager.GetString("spleen_08x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT /*
        ///COMMENT  * Spleen 12x24 1.9.1
        ///COMMENT  * Copyright (c) 2018-2021, Frederic Cambus
        ///COMMENT  * https://www.cambus.net/
        ///COMMENT  *
        ///COMMENT  * Created:      2018-08-15
        ///COMMENT  * Last Updated: 2020-10-10
        ///COMMENT  *
        ///COMMENT  * Spleen is released under the BSD 2-Clause license.
        ///COMMENT  * See LICENSE file for details.
        ///COMMENT  */
        ///FONT -misc-spleen-medium-r-normal--24-240-72-72-C-120-ISO10646-1
        ///SIZE 24 72 72
        ///FONTBOUNDINGBOX 12 24 0 -5
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Spleen&quot;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string spleen_12x24 {
            get {
                return ResourceManager.GetString("spleen_12x24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT /*
        ///COMMENT  * Spleen 16x32 1.9.1
        ///COMMENT  * Copyright (c) 2018-2021, Frederic Cambus
        ///COMMENT  * https://www.cambus.net/
        ///COMMENT  *
        ///COMMENT  * Created:      2018-08-12
        ///COMMENT  * Last Updated: 2020-10-10
        ///COMMENT  *
        ///COMMENT  * Spleen is released under the BSD 2-Clause license.
        ///COMMENT  * See LICENSE file for details.
        ///COMMENT  */
        ///FONT -misc-spleen-medium-r-normal--32-320-72-72-C-160-ISO10646-1
        ///SIZE 32 72 72
        ///FONTBOUNDINGBOX 16 32 0 -6
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Spleen&quot;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string spleen_16x32 {
            get {
                return ResourceManager.GetString("spleen_16x32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT /*
        ///COMMENT  * Spleen 32x64 1.9.1
        ///COMMENT  * Copyright (c) 2018-2021, Frederic Cambus
        ///COMMENT  * https://www.cambus.net/
        ///COMMENT  *
        ///COMMENT  * Created:      2018-09-11
        ///COMMENT  * Last Updated: 2020-10-10
        ///COMMENT  *
        ///COMMENT  * Spleen is released under the BSD 2-Clause license.
        ///COMMENT  * See LICENSE file for details.
        ///COMMENT  */
        ///FONT -misc-spleen-medium-r-normal--64-640-72-72-C-320-ISO10646-1
        ///SIZE 64 72 72
        ///FONTBOUNDINGBOX 32 64 0 -12
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Spleen[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string spleen_32x64 {
            get {
                return ResourceManager.GetString("spleen_32x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///FONT -Raccoon-Fixed4x6-Medium-R-Normal--6-60-75-75-P-40-ISO10646-1
        ///SIZE 6 75 75
        ///FONTBOUNDINGBOX 3 6 0 -1
        ///STARTPROPERTIES 25
        ///FONT_NAME &quot;Fixed4x6&quot;
        ///FONT_ASCENT 5
        ///FONT_DESCENT 1
        ///QUAD_WIDTH 6
        ///X_HEIGHT 3
        ///CAP_HEIGHT 4
        ///FONTNAME_REGISTRY &quot;&quot;
        ///FAMILY_NAME &quot;Fixed4x6&quot;
        ///FOUNDRY &quot;Raccoon&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///SLANT &quot;R&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///PIXEL_SIZE 6
        ///POINT_SIZE 60
        ///RESOLUTION_X 75
        ///RESOLUTION_Y 75
        ///RESOLUTION 75
        ///SPACING &quot;P&quot;
        ///AVERAGE_WIDTH 40
        ///CHARSET_REGISTRY &quot;ISO10646[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tom_thumb {
            get {
                return ResourceManager.GetString("tom_thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT Copyright (C) 1997-2020  MAMEDev and contributors
        ///FONT -mamedev-uismall-Medium-R-Normal--16-120-96-96-P-100-ISO10646-1
        ///SIZE 12 96 96
        ///FONTBOUNDINGBOX 8 11 0 -2
        ///STARTPROPERTIES 18
        ///POINT_SIZE 120
        ///PIXEL_SIZE 16
        ///RESOLUTION_X 96
        ///RESOLUTION_Y 96
        ///FONT_ASCENT 9
        ///FONT_DESCENT 2
        ///AVERAGE_WIDTH 100
        ///SPACING &quot;P&quot;
        ///_GBDFED_INFO &quot;Edited with gbdfed 1.5.&quot;
        ///FOUNDRY &quot;mamedev&quot;
        ///FAMILY_NAME &quot;uismall&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string uismall {
            get {
                return ResourceManager.GetString("uismall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///FONT -gnu-Unifont-Medium-R-Normal-Sans-16-160-75-75-c-80-iso10646-1
        ///SIZE 16 75 75
        ///FONTBOUNDINGBOX 16 16 0 -2
        ///STARTPROPERTIES 24
        ///COPYRIGHT &quot;Copyright (C) 1998-2021 Roman Czyborra, Paul Hardy, Qianqian Fang, Andrew Miller, Johnnie Weaver, David Corbett, Nils Moskopp, Rebecca Bettencourt, et al. License: SIL Open Font License version 1.1 and GPLv2+: GNU GPL version 2 or later &lt;http://gnu.org/licenses/gpl.html&gt; with the GNU Font Embedding Exception.&quot;
        ///FONT_VERSION &quot;13.0.06&quot;
        ///FONT_TYPE &quot;Bitmap[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string unifont_13_0_06_bdf {
            get {
                return ResourceManager.GetString("unifont_13_0_06_bdf", resourceCulture);
            }
        }
    }
}
