//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShimLib.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShimLib.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_04x06 {
            get {
                object obj = ResourceManager.GetObject("Raster_04x06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_05x08 {
            get {
                object obj = ResourceManager.GetObject("Raster_05x08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_05x12 {
            get {
                object obj = ResourceManager.GetObject("Raster_05x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_06x08 {
            get {
                object obj = ResourceManager.GetObject("Raster_06x08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_06x13 {
            get {
                object obj = ResourceManager.GetObject("Raster_06x13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_07x12 {
            get {
                object obj = ResourceManager.GetObject("Raster_07x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_08x08 {
            get {
                object obj = ResourceManager.GetObject("Raster_08x08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_08x12 {
            get {
                object obj = ResourceManager.GetObject("Raster_08x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_08x16 {
            get {
                object obj = ResourceManager.GetObject("Raster_08x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_08x18 {
            get {
                object obj = ResourceManager.GetObject("Raster_08x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_10x18 {
            get {
                object obj = ResourceManager.GetObject("Raster_10x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_10x20 {
            get {
                object obj = ResourceManager.GetObject("Raster_10x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_10x22 {
            get {
                object obj = ResourceManager.GetObject("Raster_10x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_12x16 {
            get {
                object obj = ResourceManager.GetObject("Raster_12x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_12x27 {
            get {
                object obj = ResourceManager.GetObject("Raster_12x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_16x08 {
            get {
                object obj = ResourceManager.GetObject("Raster_16x08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Raster_16x12 {
            get {
                object obj = ResourceManager.GetObject("Raster_16x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT Copyright (C) 1997-2020  MAMEDev and contributors
        ///FONT -mamedev-uismall-Medium-R-Normal--16-120-96-96-P-100-ISO10646-1
        ///SIZE 12 96 96
        ///FONTBOUNDINGBOX 8 11 0 -2
        ///STARTPROPERTIES 18
        ///POINT_SIZE 120
        ///PIXEL_SIZE 16
        ///RESOLUTION_X 96
        ///RESOLUTION_Y 96
        ///FONT_ASCENT 9
        ///FONT_DESCENT 2
        ///AVERAGE_WIDTH 100
        ///SPACING &quot;P&quot;
        ///_GBDFED_INFO &quot;Edited with gbdfed 1.5.&quot;
        ///FOUNDRY &quot;mamedev&quot;
        ///FAMILY_NAME &quot;uismall&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string uismall {
            get {
                return ResourceManager.GetString("uismall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0000:AAAA00018000000180004A51EA505A51C99E0001800000018000000180005555
        ///0001:AAAA00018000000180003993C252325F8A527193800000018000000180005555
        ///0002:AAAA00018000000180003BA5C124311989247125800000018000000180005555
        ///0003:AAAA00018000000180007BA5C1247919C1247925800000018000000180005555
        ///0004:AAAA000180000001800079BFC2487A49C2487989800000018000000180005555
        ///0005:AAAA00018000000180007A4DC2527B53C2D67A4F800000018000000180005555
        ///0006:AAAA000180000001800031A5CA287A31CA2849A5800000018000000180005555
        ///0007:AAAA000180[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string unifont_13_0_06_hex {
            get {
                return ResourceManager.GetString("unifont_13_0_06_hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ## Version Info
        ///
        ///### V1.0.0.0 - 2021.05.28
        ///1. todo.txt Solution Item폴더로 이동
        ///2. VersionInfo.md 리소스 추가 및 설정창에 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
    }
}
