//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShimLib.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShimLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///FONT -aaron-bitocra7-Medium-R-Normal--7-60-75-75-C-40-ISO8859-1
        ///SIZE 7 75 75
        ///FONTBOUNDINGBOX 4 7 0 -1
        ///STARTPROPERTIES 24
        ///FONTNAME_REGISTRY &quot;&quot;
        ///FOUNDRY &quot;aaron&quot;
        ///FAMILY_NAME &quot;bitocra7&quot;
        ///FACE_NAME &quot;bitocra7&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///PIXEL_SIZE 7
        ///POINT_SIZE 60
        ///RESOLUTION_X 75
        ///RESOLUTION_Y 75
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 40
        ///CHARSET_REGISTRY &quot;ISO8859&quot;
        ///CHARSET_ENCODING &quot;1&quot;
        ///COPYRIGHT &quot;Aaron Christianson 2011&quot;
        ///WEIGHT 10
        ///X_HEIGHT 5
        ///QUAD_WI[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string bitocra7 {
            get {
                return ResourceManager.GetString("bitocra7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///FONT -benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1
        ///SIZE 10 75 75
        ///FONTBOUNDINGBOX 10 12 -2 -3
        ///STARTPROPERTIES 26
        ///FONTNAME_REGISTRY &quot;&quot;
        ///FOUNDRY &quot;artwiz&quot;
        ///FAMILY_NAME &quot;lemon&quot;
        ///WEIGHT_NAME &quot;medium&quot;
        ///SLANT &quot;r&quot;
        ///SETWIDTH_NAME &quot;normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///PIXEL_SIZE 10
        ///POINT_SIZE 110
        ///RESOLUTION_X 75
        ///RESOLUTION_Y 75
        ///SPACING &quot;m&quot;
        ///AVERAGE_WIDTH 50
        ///CHARSET_REGISTRY &quot;ISO8859&quot;
        ///CHARSET_ENCODING &quot;1&quot;
        ///OPYRIGHT &quot;artwiz, fixed by aleczapka&quot;
        ///FACE_NAME &quot;lemon&quot;
        ///WEIGHT 10
        ///X_HEIGHT 6
        ///QUAD_[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lemon {
            get {
                return ResourceManager.GetString("lemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u12b
        ///FONT -xos4-Terminus-Bold-R-Normal--12-120-72-72-C-60-ISO10646-1
        ///SIZE 12 72 72
        ///FONTBOUNDINGBOX 6 12 0 -2
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 12
        ///POINT_SIZE 120
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 60
        ///CHARSET_REGISTRY &quot;ISO10[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u12b {
            get {
                return ResourceManager.GetString("ter_u12b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u12n
        ///FONT -xos4-Terminus-Medium-R-Normal--12-120-72-72-C-60-ISO10646-1
        ///SIZE 12 72 72
        ///FONTBOUNDINGBOX 6 12 0 -2
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 12
        ///POINT_SIZE 120
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 60
        ///CHARSET_REGISTRY &quot;I[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u12n {
            get {
                return ResourceManager.GetString("ter_u12n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u14b
        ///FONT -xos4-Terminus-Bold-R-Normal--14-140-72-72-C-80-ISO10646-1
        ///SIZE 14 72 72
        ///FONTBOUNDINGBOX 8 14 0 -2
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 14
        ///POINT_SIZE 140
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 80
        ///CHARSET_REGISTRY &quot;ISO10[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u14b {
            get {
                return ResourceManager.GetString("ter_u14b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u14n
        ///FONT -xos4-Terminus-Medium-R-Normal--14-140-72-72-C-80-ISO10646-1
        ///SIZE 14 72 72
        ///FONTBOUNDINGBOX 8 14 0 -2
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 14
        ///POINT_SIZE 140
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 80
        ///CHARSET_REGISTRY &quot;I[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u14n {
            get {
                return ResourceManager.GetString("ter_u14n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u16b
        ///FONT -xos4-Terminus-Bold-R-Normal--16-160-72-72-C-80-ISO10646-1
        ///SIZE 16 72 72
        ///FONTBOUNDINGBOX 8 16 0 -4
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 16
        ///POINT_SIZE 160
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 80
        ///CHARSET_REGISTRY &quot;ISO10[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u16b {
            get {
                return ResourceManager.GetString("ter_u16b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u16n
        ///FONT -xos4-Terminus-Medium-R-Normal--16-160-72-72-C-80-ISO10646-1
        ///SIZE 16 72 72
        ///FONTBOUNDINGBOX 8 16 0 -4
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 16
        ///POINT_SIZE 160
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 80
        ///CHARSET_REGISTRY &quot;I[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u16n {
            get {
                return ResourceManager.GetString("ter_u16n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u18b
        ///FONT -xos4-Terminus-Bold-R-Normal--18-180-72-72-C-100-ISO10646-1
        ///SIZE 18 72 72
        ///FONTBOUNDINGBOX 10 18 0 -3
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 18
        ///POINT_SIZE 180
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 100
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u18b {
            get {
                return ResourceManager.GetString("ter_u18b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u18n
        ///FONT -xos4-Terminus-Medium-R-Normal--18-180-72-72-C-100-ISO10646-1
        ///SIZE 18 72 72
        ///FONTBOUNDINGBOX 10 18 0 -3
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 18
        ///POINT_SIZE 180
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 100
        ///CHARSET_REGISTRY[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u18n {
            get {
                return ResourceManager.GetString("ter_u18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u20b
        ///FONT -xos4-Terminus-Bold-R-Normal--20-200-72-72-C-100-ISO10646-1
        ///SIZE 20 72 72
        ///FONTBOUNDINGBOX 10 20 0 -4
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 20
        ///POINT_SIZE 200
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 100
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u20b {
            get {
                return ResourceManager.GetString("ter_u20b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u20n
        ///FONT -xos4-Terminus-Medium-R-Normal--20-200-72-72-C-100-ISO10646-1
        ///SIZE 20 72 72
        ///FONTBOUNDINGBOX 10 20 0 -4
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 20
        ///POINT_SIZE 200
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 100
        ///CHARSET_REGISTRY[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u20n {
            get {
                return ResourceManager.GetString("ter_u20n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u22b
        ///FONT -xos4-Terminus-Bold-R-Normal--22-220-72-72-C-110-ISO10646-1
        ///SIZE 22 72 72
        ///FONTBOUNDINGBOX 11 22 0 -5
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 22
        ///POINT_SIZE 220
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 110
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u22b {
            get {
                return ResourceManager.GetString("ter_u22b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u22n
        ///FONT -xos4-Terminus-Medium-R-Normal--22-220-72-72-C-110-ISO10646-1
        ///SIZE 22 72 72
        ///FONTBOUNDINGBOX 11 22 0 -5
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 22
        ///POINT_SIZE 220
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 110
        ///CHARSET_REGISTRY[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u22n {
            get {
                return ResourceManager.GetString("ter_u22n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u24b
        ///FONT -xos4-Terminus-Bold-R-Normal--24-240-72-72-C-120-ISO10646-1
        ///SIZE 24 72 72
        ///FONTBOUNDINGBOX 12 24 0 -5
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 24
        ///POINT_SIZE 240
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 120
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u24b {
            get {
                return ResourceManager.GetString("ter_u24b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u24n
        ///FONT -xos4-Terminus-Medium-R-Normal--24-240-72-72-C-120-ISO10646-1
        ///SIZE 24 72 72
        ///FONTBOUNDINGBOX 12 24 0 -5
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 24
        ///POINT_SIZE 240
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 120
        ///CHARSET_REGISTRY[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u24n {
            get {
                return ResourceManager.GetString("ter_u24n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u28b
        ///FONT -xos4-Terminus-Bold-R-Normal--28-280-72-72-C-140-ISO10646-1
        ///SIZE 28 72 72
        ///FONTBOUNDINGBOX 14 28 0 -6
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 28
        ///POINT_SIZE 280
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 140
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u28b {
            get {
                return ResourceManager.GetString("ter_u28b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u28n
        ///FONT -xos4-Terminus-Medium-R-Normal--28-280-72-72-C-140-ISO10646-1
        ///SIZE 28 72 72
        ///FONTBOUNDINGBOX 14 28 0 -6
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 28
        ///POINT_SIZE 280
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 140
        ///CHARSET_REGISTRY[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u28n {
            get {
                return ResourceManager.GetString("ter_u28n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u32b
        ///FONT -xos4-Terminus-Bold-R-Normal--32-320-72-72-C-160-ISO10646-1
        ///SIZE 32 72 72
        ///FONTBOUNDINGBOX 16 32 0 -6
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Bold&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 32
        ///POINT_SIZE 320
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 160
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u32b {
            get {
                return ResourceManager.GetString("ter_u32b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT ter-u32n
        ///FONT -xos4-Terminus-Medium-R-Normal--32-320-72-72-C-160-ISO10646-1
        ///SIZE 32 72 72
        ///FONTBOUNDINGBOX 16 32 0 -6
        ///STARTPROPERTIES 20
        ///FAMILY_NAME &quot;Terminus&quot;
        ///FOUNDRY &quot;xos4&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///COPYRIGHT &quot;Copyright (C) 2014 Dimitar Toshkov Zhekov&quot;
        ///NOTICE &quot;Licensed under the SIL Open Font License, Version 1.1&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///PIXEL_SIZE 32
        ///POINT_SIZE 320
        ///RESOLUTION_X 72
        ///RESOLUTION_Y 72
        ///SPACING &quot;C&quot;
        ///AVERAGE_WIDTH 160
        ///CHARSET_REGISTRY[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ter_u32n {
            get {
                return ResourceManager.GetString("ter_u32n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///COMMENT Copyright (C) 1997-2020  MAMEDev and contributors
        ///FONT -mamedev-uismall-Medium-R-Normal--16-120-96-96-P-100-ISO10646-1
        ///SIZE 12 96 96
        ///FONTBOUNDINGBOX 8 11 0 -2
        ///STARTPROPERTIES 18
        ///POINT_SIZE 120
        ///PIXEL_SIZE 16
        ///RESOLUTION_X 96
        ///RESOLUTION_Y 96
        ///FONT_ASCENT 9
        ///FONT_DESCENT 2
        ///AVERAGE_WIDTH 100
        ///SPACING &quot;P&quot;
        ///_GBDFED_INFO &quot;Edited with gbdfed 1.5.&quot;
        ///FOUNDRY &quot;mamedev&quot;
        ///FAMILY_NAME &quot;uismall&quot;
        ///WEIGHT_NAME &quot;Medium&quot;
        ///SLANT &quot;R&quot;
        ///SETWIDTH_NAME &quot;Normal&quot;
        ///ADD_STYLE_NAME &quot;&quot;
        ///CHARSET_REGISTRY &quot;IS[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string uismall {
            get {
                return ResourceManager.GetString("uismall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] unifont_13_0_06 {
            get {
                object obj = ResourceManager.GetObject("unifont_13_0_06", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   STARTFONT 2.1
        ///FONT -gnu-Unifont-Medium-R-Normal-Sans-16-160-75-75-c-80-iso10646-1
        ///SIZE 16 75 75
        ///FONTBOUNDINGBOX 16 16 0 -2
        ///STARTPROPERTIES 24
        ///COPYRIGHT &quot;Copyright (C) 1998-2021 Roman Czyborra, Paul Hardy, Qianqian Fang, Andrew Miller, Johnnie Weaver, David Corbett, Nils Moskopp, Rebecca Bettencourt, et al. License: SIL Open Font License version 1.1 and GPLv2+: GNU GPL version 2 or later &lt;http://gnu.org/licenses/gpl.html&gt; with the GNU Font Embedding Exception.&quot;
        ///FONT_VERSION &quot;13.0.06&quot;
        ///FONT_TYPE &quot;Bitmap[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string unifont_13_0_06_bdf {
            get {
                return ResourceManager.GetString("unifont_13_0_06_bdf", resourceCulture);
            }
        }
    }
}
